default:
    just -l

build +VER:
    cargo build --bin {{VER}}

run +VER:
    cargo run --bin {{VER}}

runr +VER:
    cargo run --release --bin {{VER}}

fmt:
    cargo fmt

lint:
    cargo clippy --all-targets --locked --workspace -- -D warnings

clean:
    cargo clean
