default:
    just -l

build +VER:
    mkdir -p build
    cd build && zig build-exe ../{{VER}}.zig --name {{VER}}.x

run +VER:
    just build {{VER}}
    ./build/{{VER}}.x

clean:
    rm -rf *.o *.x build
